version: 1.0.{build}

os: Visual Studio 2015
platform: Any CPU
configuration: Release
build:
  project: LukeNet.sln
init:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)
before_build:
  - ps: nuget restore
after_build:
  - 7z a LukeNet.zip %APPVEYOR_BUILD_FOLDER%\Luke.Net\bin\Release\* -r -x!*.pdb -x!*.xml

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(GIT_HASH)-$(APPVEYOR_REPO_BRANCH)'

shallow_clone: true
cache:
  - packages -> **\packages.config

test: off

artifacts:
  - path: 'LukeNet.zip'
    name: release_archive

deploy:
- provider: GitHub
  auth_token:
    secure: DI098SO7LeSl0fwnw3kqTm7mdyyH+84meGFWzam0ksoRy4sd0ng8dEsrjV+ub1nm
  tag: '$(APPVEYOR_REPO_TAG_NAME)'
  artifact: release_archive
  draft: true
  force_update: true
  on:
    appveyor_repo_tag: true
